import type { NFLTeam } from "@/types"

// Mock NFL teams data
export const NFL_TEAMS: NFLTeam[] = [
  // AFC East
  {
    id: "buf",
    name: "Bills",
    city: "Buffalo",
    abbreviation: "BUF",
    primaryColor: "#00338D",
    secondaryColor: "#C60C30",
    conference: "AFC",
    division: "East",
  },
  {
    id: "mia",
    name: "Dolphins",
    city: "Miami",
    abbreviation: "MIA",
    primaryColor: "#008E97",
    secondaryColor: "#FC4C02",
    conference: "AFC",
    division: "East",
  },
  {
    id: "ne",
    name: "Patriots",
    city: "New England",
    abbreviation: "NE",
    primaryColor: "#002244",
    secondaryColor: "#C60C30",
    conference: "AFC",
    division: "East",
  },
  {
    id: "nyj",
    name: "Jets",
    city: "New York",
    abbreviation: "NYJ",
    primaryColor: "#125740",
    secondaryColor: "#000000",
    conference: "AFC",
    division: "East",
  },

  // AFC North
  {
    id: "bal",
    name: "Ravens",
    city: "Baltimore",
    abbreviation: "BAL",
    primaryColor: "#241773",
    secondaryColor: "#000000",
    conference: "AFC",
    division: "North",
  },
  {
    id: "cin",
    name: "Bengals",
    city: "Cincinnati",
    abbreviation: "CIN",
    primaryColor: "#FB4F14",
    secondaryColor: "#000000",
    conference: "AFC",
    division: "North",
  },
  {
    id: "cle",
    name: "Browns",
    city: "Cleveland",
    abbreviation: "CLE",
    primaryColor: "#311D00",
    secondaryColor: "#FF3C00",
    conference: "AFC",
    division: "North",
  },
  {
    id: "pit",
    name: "Steelers",
    city: "Pittsburgh",
    abbreviation: "PIT",
    primaryColor: "#FFB612",
    secondaryColor: "#000000",
    conference: "AFC",
    division: "North",
  },

  // AFC South
  {
    id: "hou",
    name: "Texans",
    city: "Houston",
    abbreviation: "HOU",
    primaryColor: "#03202F",
    secondaryColor: "#A71930",
    conference: "AFC",
    division: "South",
  },
  {
    id: "ind",
    name: "Colts",
    city: "Indianapolis",
    abbreviation: "IND",
    primaryColor: "#002C5F",
    secondaryColor: "#A2AAAD",
    conference: "AFC",
    division: "South",
  },
  {
    id: "jax",
    name: "Jaguars",
    city: "Jacksonville",
    abbreviation: "JAX",
    primaryColor: "#006778",
    secondaryColor: "#9F792C",
    conference: "AFC",
    division: "South",
  },
  {
    id: "ten",
    name: "Titans",
    city: "Tennessee",
    abbreviation: "TEN",
    primaryColor: "#0C2340",
    secondaryColor: "#4B92DB",
    conference: "AFC",
    division: "South",
  },

  // AFC West
  {
    id: "den",
    name: "Broncos",
    city: "Denver",
    abbreviation: "DEN",
    primaryColor: "#FB4F14",
    secondaryColor: "#002244",
    conference: "AFC",
    division: "West",
  },
  {
    id: "kc",
    name: "Chiefs",
    city: "Kansas City",
    abbreviation: "KC",
    primaryColor: "#E31837",
    secondaryColor: "#FFB81C",
    conference: "AFC",
    division: "West",
  },
  {
    id: "lv",
    name: "Raiders",
    city: "Las Vegas",
    abbreviation: "LV",
    primaryColor: "#000000",
    secondaryColor: "#A5ACAF",
    conference: "AFC",
    division: "West",
  },
  {
    id: "lac",
    name: "Chargers",
    city: "Los Angeles",
    abbreviation: "LAC",
    primaryColor: "#0080C6",
    secondaryColor: "#FFC20E",
    conference: "AFC",
    division: "West",
  },

  // NFC East
  {
    id: "dal",
    name: "Cowboys",
    city: "Dallas",
    abbreviation: "DAL",
    primaryColor: "#003594",
    secondaryColor: "#041E42",
    conference: "NFC",
    division: "East",
  },
  {
    id: "nyg",
    name: "Giants",
    city: "New York",
    abbreviation: "NYG",
    primaryColor: "#0B2265",
    secondaryColor: "#A71930",
    conference: "NFC",
    division: "East",
  },
  {
    id: "phi",
    name: "Eagles",
    city: "Philadelphia",
    abbreviation: "PHI",
    primaryColor: "#004C54",
    secondaryColor: "#A5ACAF",
    conference: "NFC",
    division: "East",
  },
  {
    id: "was",
    name: "Commanders",
    city: "Washington",
    abbreviation: "WAS",
    primaryColor: "#5A1414",
    secondaryColor: "#FFB612",
    conference: "NFC",
    division: "East",
  },

  // NFC North
  {
    id: "chi",
    name: "Bears",
    city: "Chicago",
    abbreviation: "CHI",
    primaryColor: "#0B162A",
    secondaryColor: "#C83803",
    conference: "NFC",
    division: "North",
  },
  {
    id: "det",
    name: "Lions",
    city: "Detroit",
    abbreviation: "DET",
    primaryColor: "#0076B6",
    secondaryColor: "#B0B7BC",
    conference: "NFC",
    division: "North",
  },
  {
    id: "gb",
    name: "Packers",
    city: "Green Bay",
    abbreviation: "GB",
    primaryColor: "#203731",
    secondaryColor: "#FFB612",
    conference: "NFC",
    division: "North",
  },
  {
    id: "min",
    name: "Vikings",
    city: "Minnesota",
    abbreviation: "MIN",
    primaryColor: "#4F2683",
    secondaryColor: "#FFC62F",
    conference: "NFC",
    division: "North",
  },

  // NFC South
  {
    id: "atl",
    name: "Falcons",
    city: "Atlanta",
    abbreviation: "ATL",
    primaryColor: "#A71930",
    secondaryColor: "#000000",
    conference: "NFC",
    division: "South",
  },
  {
    id: "car",
    name: "Panthers",
    city: "Carolina",
    abbreviation: "CAR",
    primaryColor: "#0085CA",
    secondaryColor: "#101820",
    conference: "NFC",
    division: "South",
  },
  {
    id: "no",
    name: "Saints",
    city: "New Orleans",
    abbreviation: "NO",
    primaryColor: "#D3BC8D",
    secondaryColor: "#101820",
    conference: "NFC",
    division: "South",
  },
  {
    id: "tb",
    name: "Buccaneers",
    city: "Tampa Bay",
    abbreviation: "TB",
    primaryColor: "#D50A0A",
    secondaryColor: "#FF7900",
    conference: "NFC",
    division: "South",
  },

  // NFC West
  {
    id: "ari",
    name: "Cardinals",
    city: "Arizona",
    abbreviation: "ARI",
    primaryColor: "#97233F",
    secondaryColor: "#000000",
    conference: "NFC",
    division: "West",
  },
  {
    id: "lar",
    name: "Rams",
    city: "Los Angeles",
    abbreviation: "LAR",
    primaryColor: "#003594",
    secondaryColor: "#FFA300",
    conference: "NFC",
    division: "West",
  },
  {
    id: "sf",
    name: "49ers",
    city: "San Francisco",
    abbreviation: "SF",
    primaryColor: "#AA0000",
    secondaryColor: "#B3995D",
    conference: "NFC",
    division: "West",
  },
  {
    id: "sea",
    name: "Seahawks",
    city: "Seattle",
    abbreviation: "SEA",
    primaryColor: "#002244",
    secondaryColor: "#69BE28",
    conference: "NFC",
    division: "West",
  },
]

// Mock data for predictions and stats
export const mockPredictionData = {
  teamA_win_prob: 65.2,
  teamB_win_prob: 34.8,
  confidence: 78,
  key_factors: [
    { name: "EPA per Play", value: 0.15, description: "Expected Points Added per play differential favors Team A" },
    { name: "Momentum Score", value: 85, description: "Recent performance and trend analysis" },
    { name: "Strength of Schedule", value: 72, description: "Quality of opponents faced this season" },
    { name: "Recent Form", value: 80, description: "Performance in last 5 games" },
    { name: "Head-to-Head", value: 60, description: "Historical matchup performance" },
  ],
}

export const mockTeamStats = {
  teamA: {
    name: "Kansas City Chiefs",
    record: "11-3",
    epa_per_play: 0.18,
    success_rate: 48.2,
    recent_form: ["W", "W", "L", "W", "W"] as Array<"W" | "L">,
    momentum_score: 85,
  },
  teamB: {
    name: "Buffalo Bills",
    record: "10-4",
    epa_per_play: 0.12,
    success_rate: 45.8,
    recent_form: ["W", "L", "W", "W", "L"] as Array<"W" | "L">,
    momentum_score: 72,
  },
}
